name: load-rs::sync dev-stable branches

# The goal of this workflow is to create PR with changes of load-rs script itself
#   from iroha2-dev branch because we need to keep the same rust source code for all script versions
# Ignore changes to Cargo.toml since this file should be updated from load-rs::bump-dependencies workflow
# No need to touch iroha2-lts branch because it is updated once per six months and should be stable

on:
 pull_request:
  branches: [iroha2-dev]
  types: [closed]

jobs:
  merge_iroha2-dev_to_iroha2-stable:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Filter files to be merged
        uses: dorny/paths-filter@v2.11.1
        id: filter
        with:
          filters: |
            cargo:
              - 'Cargo.toml'
      - name: Create pull request
        if: steps.filter.outputs.cargo == 'false'
        uses: repo-sync/pull-request@v2.9
        with:
          source_branch: "iroha2-dev"
          destination_branch: "iroha2-stable"
          pr_title: "Merge iroha2-dev into iroha2-stable"
          pr_body: "**Automated pull request**<br><br><p>Synchronize a changes from iroha2-dev to iroha2-stable branches</p>"
          pr_reviewer: "BAStos525,appetrosyan"
          pr_assignee: ${{ github.actor }}
          pr_label: "iroha2,load-rs,auto-pr"
